### ISSUE TITLE
Weak algorithm warning

### ISSUE THREAD

**Issue by zulfadlisukarno** [mitinsany/composer-ppa#2]
apt throwing warning message of signature uses weak algorithm key.
`W: https://mitinsany.github.io/composer-ppa/deb/dists/latest/InRelease: Signature by key B795A01CB58906D9FA104274548EE88B5D87B9A7 uses weak algorithm (dsa2048)
`

**Comment by mitinsany** [comment]
Thanks for the issue. I updated the key. To continue using the repository, update this key for yourself
